[package]
name = "kadis"
version = "0.1.0"
authors = ["GiraffeKey <giraffekey@tutanota.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
async-std = "1.8"
futures = "0.3"
libp2p = "0.32"
log = "0.4"
